### PR TITLE
Use server startup detection script for better install timing of configs

### PR DESCRIPTION
**Pull request by jbornemann**
@jscelza @cculb

### CODE REVIEW

**Comment by jbornemann** [comment]
#3 should probably go in before this

**Comment by jbornemann** [comment]
#3 is merged, and this branch has been updated

**Comment by cculb** [comment]
+1

**Comment by jscelza** [comment]
+1. thanks for the demo. This fix will really help with loading updates, rep queues and osgi without needing to run puppet twice.

**Pull request merged**
