### PR TITLE
TWCable-20582 mod_pagespeed puppet install

### PR DESCRIPTION
**Pull request by brianliddle**
@GaryHowell @jdigger @fortman @cculb @KyleBaker @BrianArmstrong - Not ready for testing, but definitely would appreciate collaborative comments on this one.   Essentially, I'm trying to leverage the existing structure to install mod_pagespeed.   One assumption is that the dispatcher is already installed.  Once we can leverage this code, we'll add a verify step to make sure that it's installed and running.

### CODE REVIEW

**Comment by wobes** [comment]
We should talk about this.  interesting that it is being added to the adobe_em6 module rather then adobe_dispatcher6 module.

Adding @jbornemann

**Comment by wobes** [comment]
using execs and system calls is not the best approach here. should be leveraging a repo to install rpm not curls.  Also should be using the puppet service framework and not making "sudo" system calls.

**Comment by jbornemann** [comment]
I agree, I don't think this is the change we need. We should discuss internally. The AEM module should only be provisioning AEM. The dispatcher module should only be provisioning the dispatcher.

**Comment by jdigger** [comment]
Can I close this PR?

**Comment by fortman** [comment]
@jdigger Yes, please close this.

**Pull request closed without merging**
